// export { default as Button } from './Button';
export { default as Buzz } from './Buzz';
export { default as DashBoard } from './DashBoard';
export { default as Directory } from './Directory';
export { default as Leave } from './Leave';
export { default as Maintenance } from './Maintenance';
export { default as MyInfo } from './MyInfo';
export { default as PIM } from './PIM';
export { default as Search } from './Search';
export { default as Time } from './Time';
